### ISSUE TITLE
Linking to Webaddress

### ISSUE THREAD

**Issue by dsm320** [Nerdmind/Blog#11]
Nerdmind,

Perhaps I am missing it in the documentation but where/how can we link this blog site to a web address?  Additionally, if I already have a website created is there an easy way to simply add the blog as a separate page? Thank you for any help you can offer in this matter.

**Comment by Nerdmind** [comment]
Hi dsm320,

I don't really understand your problem. Do you want to install the system in a sub directory of an existing website? This is possible if you override `PATHINFO.BASE` in your `configuration.php`. See the wiki: https://github.com/Nerdmind/Blog/wiki/Configuration#paths

## Example
If your existing website is available through `https://example.com`, then you can create a sub directory in the document root which contains the blog. For example: `https://example.com/blog/`. In your `configuration.php` you have to define this:

`Application::set('PATHINFO.BASE', 'blog/');`

**Comment by dsm320** [comment]
Thank you very much. That solved my issue.
