### ISSUE TITLE
Help Needed

### ISSUE THREAD

**Issue by paul-jonez** [Nerdmind/Blog#14]
Please I need your assistance here on this blog script.

After following the installation guide, this is what I keep getting when I try to run it on the browser:

"Parse error: syntax error, unexpected '?' in C:\xampp\htdocs\icode\learn\exercises\to_clone\Blog-master\admin\auth.php on line 49".

Please how do I go about solving this?

Thank you.

**Comment by Nerdmind** [comment]
Hi. Are you using at least PHP 7? I don't see a `?` on [`auth.php` at line 49](https://github.com/Nerdmind/Blog/blob/0a49f259b687aba010dd2edfcdf73d040622b561/admin/auth.php#L49).
