### ISSUE TITLE
This script not working in subfolder

### ISSUE THREAD

**Issue by dillo1618** [Nerdmind/Blog#18]
This script can not embed into CMS because it not working if  put it to subfolder, all root paths will invalid.

**Comment by Nerdmind** [comment]
Have you specified [`PATHINFO.BASE`](https://github.com/Nerdmind/Blog/wiki/Configuration/d7fa3b949171785c8efb130cd2e90daf33f02c1a#paths)?

**Comment by dillo1618** [comment]
I change define('ROOT', dirname(__DIR__).'/'); to subfolder in core/application.php, js and css path invalid, but navigation link ok.

**Comment by dillo1618** [comment]
> Have you specified [`PATHINFO.BASE`](https://github.com/Nerdmind/Blog/wiki/Configuration/d7fa3b949171785c8efb130cd2e90daf33f02c1a#paths)?

OK. Thank you.

**Comment by Nerdmind** [comment]
No problem.
If this solved the problem, please close the issue.
