### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by jagallardo11** [Nerdmind/Blog#4]
Help I get this error when executing the project
Parse error: syntax error, unexpected 'exit' (T_EXIT) in \core\application.php on line 27

**Comment by Nerdmind** [comment]
Hi. I cannot reproduce this error if I clone the repository, adjust the configuration file and execute it. Are you running it with PHP7? o.O

**Comment by Nerdmind** [comment]
Hmm. I close this because there was no response within a month.

**Comment by GaneshKandu** [comment]
Hi Getting same issue 

**Parse error**: syntax error, unexpected 'exit' (T_EXIT) in **core/application.php** on line **28**
on PHP version less than 7.0 working on PHP 7.0

**Comment by Nerdmind** [comment]
Hi. Thanks for your feedback. But the system needs at least PHP 7:
_"Simple blogging application written with pure **PHP7**!"_
