### ISSUE TITLE
What a WONDERFULL script

### ISSUE THREAD

**Issue by RoyalC** [Nerdmind/Blog#7]
hello, you made a wonderfull script
Some features might be interressing like

- Event Calendar
- Private message

etc.
i'm sure it will be THE BLOG script of the future .

**Comment by Nerdmind** [comment]
Hi. Thank you for your feedback! Can you explain "Private message" in more detail? Please note that there is currently no real user permission system (every user can do anything yet – but that can change in the future, I hope so). An "Event Calendar" sounds like a thing that is very user-specific. I don't think, that a blog system _needs_ such a thing.

The thing is: I'd like to keep it small and simple. More features means more complexity and more code to maintain. It should only contain the absolutely necessary functions of a blog system (a commentary system is already on my mind, see #5). If someone needs a blog system with many features and plugins like WordPress, then this is the wrong system for him.

**Comment by RoyalC** [comment]
private messaging system , for users 
i'm making a full translation in french, sending it tomorrow

**Comment by RoyalC** [comment]
you are right, your blog must stay simple for light and flexible using.

**Comment by Nerdmind** [comment]
A _user_ is currently the same as an _author_. You can create another user and publish posts and pages with this user. It isn't _really_ a multi-user application with a role based permission system yet. But, for example, if someone has a friend who want to publish a guest post on the blog, then a new users can be created. The guest author doesn't _need_ to know the password for the login; it is just for displaying the name of the author on a post or page (and a description of the author).

I don't see the use of a private message system for users like you describe it. If there is a role based permission system in the future (I don't know yet, it's just a hobby project and I currently don't have much time for coding) and another user would like to contact another one, he can just send an email to the email address of the other user.

**French translation:**  
Cool! Please translate the strings as accurately as possible.
