### ISSUE TITLE
Notice: Undefined index: REQUEST_SCHEME incore/application.php on line 55

### ISSUE THREAD

**Issue by GaneshKandu** [Nerdmind/Blog#8]
Hi Getting following error

**Notice:** Undefined index: REQUEST_SCHEME **incore/application.php** on line **55**

PHP 7.0
Apache 2.2.31

```
does not work with Apache 2.2
become available until Apache 2.4
```

**Comment by Nerdmind** [comment]
Hi. Thank you for this report. This problem has been fixed by using the fallback value `https` if `$_SERVER['REQUEST_SCHEME']` is not defined (146b74968f6a56163bf2a618addbb5a7a03f4684).
